"""Paste a complete export into static/<name>.jerryio.txt, then build and upload.

Build-time only: validates the export, removes the known editor trailer, and
converts inches/handedness/final heading to native AON poses. Speeds and editor
metadata are not emitted. The robot anchors these poses to its live starting
pose and follows them with AON PurePursuit at the routine's RPM limit.
Do not edit include/aon/generated/static-path.hpp; it is a disposable artifact.
"""
import argparse
import math
import json
from pathlib import Path


def convert(text):
    rows = []
    for number, line in enumerate(text.splitlines(), 1):
        if line.strip() == "endData":
            break
        fields = line.split(",")
        if len(fields) != 3:
            raise ValueError(f"line {number}: expected x,y,speed")
        row = tuple(float(field) for field in fields)
        if not all(math.isfinite(value) for value in row) or not 0 <= row[2] <= 127:
            raise ValueError(f"line {number}: invalid coordinates or speed")
        rows.append(row)
    else:
        raise ValueError("missing endData")
    # This export variant appends a duplicate endpoint and an editor-only point.
    if len(rows) >= 3 and rows[-3] == rows[-2] and all(r[2] == 0 for r in rows[-3:]):
        rows = rows[:-2]
    if len(rows) < 2 or rows[-1][2] != 0:
        raise ValueError("at least two points and a zero-speed endpoint are required")
    if any(row[2] == 0 for row in rows[:-1]):
        raise ValueError("internal stop markers are not supported by geometry-only following")
    if any(a[:2] == b[:2] for a, b in zip(rows, rows[1:])):
        raise ValueError("consecutive duplicate positions")
    x0, y0, _ = rows[0]
    angle = math.atan2(rows[1][1] - y0, rows[1][0] - x0)
    c, s = math.cos(angle), math.sin(angle)
    points = [((x-x0)*c + (y-y0)*s, (x-x0)*s - (y-y0)*c) for x, y, _ in rows]
    heading = math.degrees(math.atan2(points[-1][1]-points[-2][1],
                                     points[-1][0]-points[-2][0])) % 360
    return [(x, y, heading if i == len(points)-1 else 0.0) for i, (x, y) in enumerate(points)]


def render(routes, frames):
    branches = []
    frame_branches = []
    for name, points in sorted(routes.items()):
        x, y, angle = frames[name]
        frame_branches.append(f'  if (name == {json.dumps(name)}) {{ origin = {{{x:.12f}, {y:.12f}, {angle:.12f}}}; }}')
        values = ",\n".join("      {" + ", ".join(f"{v:.9f}" for v in row) + "}" for row in points)
        branches.append("  if (name == " + json.dumps(name) + ") {\n    path = {\n" + values + "\n    };\n  }")
    return '''// Generated by tools/generate-static-path.py; edit static/*.jerryio.txt.
#pragma once
#include "aon/math/pose.hpp"
#include <cmath>
#include <string_view>
#include <limits>
#include <vector>

namespace aon::generated {
// Transform editor X/Y and GPS heading with the same frame as the route.
inline Pose staticWaypointAt(const Pose& start, const Pose& editor, std::string_view name) {
  Pose origin;
''' + " else\n".join(frame_branches) + '''
  else { const double n = std::numeric_limits<double>::quiet_NaN(); return {n,n,n}; }
  constexpr double pi = 3.14159265358979323846;
  const double dx = editor.x-origin.x, dy = editor.y-origin.y;
  const double x = dx*std::cos(origin.theta)+dy*std::sin(origin.theta);
  const double y = dx*std::sin(origin.theta)-dy*std::cos(origin.theta);
  const double angle = start.theta*pi/180.0;
  return {start.x+x*std::cos(angle)-y*std::sin(angle),
          start.y+x*std::sin(angle)+y*std::cos(angle),
          start.theta+origin.theta*180.0/pi+editor.theta-90.0};
}
// Names are filenames without .jerryio.txt. Unknown names return an invalid empty route.
inline std::vector<Pose> staticPathAt(const Pose& start, std::string_view name = "path") {
  std::vector<Pose> path;
''' + " else\n".join(branches) + '''
  const double radians = start.theta * 3.14159265358979323846 / 180.0;
  const double c = std::cos(radians), s = std::sin(radians);
  for (auto& point : path) {
    const double x = point.x, y = point.y;
    point.x = start.x + x*c - y*s;
    point.y = start.y + x*s + y*c;
    point.theta += start.theta;
  }
  return path;
}
}  // namespace aon::generated
'''


def generate(source, output):
    files = sorted(source.glob("*.jerryio.txt")) if source.is_dir() else [source]
    routes = {}
    frames = {}
    for file in files:
        try:
            text = file.read_text(encoding="utf-8-sig")
            name = file.name.removesuffix(".jerryio.txt")
            routes[name] = convert(text)
            first, second = [tuple(map(float, line.split(","))) for line in text.splitlines()[:2]]
            frames[name] = (first[0], first[1], math.atan2(second[1]-first[1], second[0]-first[0]))
        except (ValueError, OSError) as error:
            raise ValueError(f"{file}: {error}") from error
    if not routes:
        raise ValueError(f"{source}: no *.jerryio.txt exports found")
    content = render(routes, frames)
    # Make checks the directory every build to catch removed/renamed exports.
    # Keep the header timestamp stable when geometry and route names are unchanged.
    if output.exists() and output.read_text(encoding="utf-8") == content:
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        generate(args.source, args.output)
    except (ValueError, OSError) as error:
        parser.exit(1, f"Static path conversion failed: {error}\n")


if __name__ == "__main__":
    main()
