"""Paste a complete export into static/path.jerryio.txt, then build and upload.

Build-time only: validates the export, removes the known editor trailer, and
converts inches/handedness/final heading to native AON poses. Speeds and editor
metadata are not emitted. The robot anchors these poses to its live starting
pose and follows them with AON PurePursuit at the routine's RPM limit.
Do not edit include/aon/generated/static-path.hpp; it is a disposable artifact.
"""
import argparse
import math
from pathlib import Path


def convert(text):
    rows = []
    for number, line in enumerate(text.splitlines(), 1):
        if line.strip() == "endData":
            break
        fields = line.split(",")
        if len(fields) != 3:
            raise ValueError(f"line {number}: expected x,y,speed")
        row = tuple(float(field) for field in fields)
        if not all(math.isfinite(value) for value in row) or not 0 <= row[2] <= 127:
            raise ValueError(f"line {number}: invalid coordinates or speed")
        rows.append(row)
    else:
        raise ValueError("missing endData")
    # This export variant appends a duplicate endpoint and an editor-only point.
    if len(rows) >= 3 and rows[-3] == rows[-2] and all(r[2] == 0 for r in rows[-3:]):
        rows = rows[:-2]
    if len(rows) < 2 or rows[-1][2] != 0:
        raise ValueError("at least two points and a zero-speed endpoint are required")
    if any(row[2] == 0 for row in rows[:-1]):
        raise ValueError("internal stop markers are not supported by geometry-only following")
    if any(a[:2] == b[:2] for a, b in zip(rows, rows[1:])):
        raise ValueError("consecutive duplicate positions")
    x0, y0, _ = rows[0]
    angle = math.atan2(rows[1][1] - y0, rows[1][0] - x0)
    c, s = math.cos(angle), math.sin(angle)
    points = [((x-x0)*c + (y-y0)*s, (x-x0)*s - (y-y0)*c) for x, y, _ in rows]
    heading = math.degrees(math.atan2(points[-1][1]-points[-2][1],
                                     points[-1][0]-points[-2][0])) % 360
    return [(x, y, heading if i == len(points)-1 else 0.0) for i, (x, y) in enumerate(points)]


def render(points):
    values = ",\n".join("    {" + ", ".join(f"{v:.9f}" for v in row) + "}" for row in points)
    return '''// Generated by tools/generate-static-path.py; edit static/path.jerryio.txt.
#pragma once
#include "aon/math/pose.hpp"
#include <cmath>
#include <vector>

namespace aon::generated {
inline std::vector<Pose> staticPathAt(const Pose& start) {
  std::vector<Pose> path{
''' + values + '''
  };
  const double radians = start.theta * 3.14159265358979323846 / 180.0;
  const double c = std::cos(radians), s = std::sin(radians);
  for (auto& point : path) {
    const double x = point.x, y = point.y;
    point.x = start.x + x*c - y*s;
    point.y = start.y + x*s + y*c;
    point.theta += start.theta;
  }
  return path;
}
}  // namespace aon::generated
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        output = render(convert(args.source.read_text(encoding="utf-8-sig")))
    except (ValueError, OSError) as error:
        parser.exit(1, f"Static path conversion failed: {error}\n")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
